apiVersion: v1
kind: ConfigMap
metadata:
  name: nexaflow-api-config
  namespace: nexaflow
data:
  ASPNETCORE_ENVIRONMENT: "Production"
  ASPNETCORE_URLS: "http://+:8080"
  Jwt__Issuer: "NexaFlow"
  Jwt__Audience: "NexaFlow.Client"
  Jwt__AccessTokenMinutes: "15"
  Jwt__RefreshTokenDays: "7"
  ConnectionStrings__Redis: "nexaflow-redis:6379"
  RabbitMq__HostName: "nexaflow-rabbitmq"
  RabbitMq__Port: "5672"
  Kafka__BootstrapServers: "nexaflow-kafka:9092"
