apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexaflow-rabbitmq
  namespace: nexaflow
  labels:
    app: nexaflow-rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nexaflow-rabbitmq
  template:
    metadata:
      labels:
        app: nexaflow-rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3-management-alpine
          ports:
            - containerPort: 5672
            - containerPort: 15672
          env:
            - name: RABBITMQ_DEFAULT_USER
              valueFrom:
                secretKeyRef:
                  name: nexaflow-api-secrets
                  key: RabbitMq__UserName
            - name: RABBITMQ_DEFAULT_PASS
              valueFrom:
                secretKeyRef:
                  name: nexaflow-api-secrets
                  key: RabbitMq__Password
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: nexaflow-rabbitmq
  namespace: nexaflow
spec:
  selector:
    app: nexaflow-rabbitmq
  ports:
    - name: amqp
      port: 5672
      targetPort: 5672
    - name: management
      port: 15672
      targetPort: 15672
