<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.11" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\NexaFlow.Application\NexaFlow.Application.csproj" />
    <ProjectReference Include="..\NexaFlow.Infrastructure\NexaFlow.Infrastructure.csproj" />
    <ProjectReference Include="..\NexaFlow.Messaging\NexaFlow.Messaging.csproj" />
    <ProjectReference Include="..\NexaFlow.Notifications\NexaFlow.Notifications.csproj" />
  </ItemGroup>

</Project>
