apiVersion: v1
kind: Service
metadata:
  name: nexaflow-api
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: nexaflow-api
  ports:
    - port: {{ .Values.api.service.port }}
      targetPort: {{ .Values.api.service.targetPort }}
